name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  branches:
    description: 'The branches'
    required: true
  template-file:
    description: 'The file used as template'
    required: true
    default: './github/dependabot.template.yml'

runs:
  using: node20
  main: dist/index.js
