name: Continuous Integration

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          branches: '6.1.x, 6.2.x, main'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
