name: Continuous Integration

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          branches: 'main,6.2.x,6.1.x'
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
